# The main config file for your Jekyll template

# Site settings
title: Nitin Savant               # used for the html title of every page
desc: >
  Nitin Savant's personal website.

url: http://www.nitinsavant.com      # put your website hosting url here
baseurl: ''                 # the subpath of your site, e.g. /blog
permalink: /:year/:title/   # how should we display posts url

# Meta settings
email: nitinsavant@gmail.com
author:
twitter_username:
github_username: nitinsavant
github_source:

# Put your ga tracking code below
google_analytics:

# Pagination settings
paginate: 5                           # number of posts to show per page
paginate_path: "/articles/page:num/"  # link scheme for articles, should be letf as is

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: Projects
    url: /projects/
    desc: Cool stuff I've worked on
  - title: Resume
    url: /resume/
    desc: My resume
  - title: About
    url: /about/
    desc: My about
  - title: Blog
    url: /blog/
    desc: My blog

# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false          # you can change this if you feel like it
  parse_block_html: true    # allow parsing html inside markdown

# Build settings
include:
  - _pages                  # all your pages can be put inside pages (except articles)
exclude:
  - README.md
  - vendor
plugins:
  - jekyll-paginate
